import type { Metadata } from "next";
import "./globals.css";
import { Lexend  } from "next/font/google";
import Provider from "./util/Provider";
export const metadata: Metadata = {
  title: "Next JS",
  description: "Generated by create next app",
};

const lexend = Lexend({
  subsets: ['latin'],
})
 


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Provider>
          {children}
          </Provider>
      </body>
    </html>
  );
}
