import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./util/Provider";
export const metadata: Metadata = {
  title: "Trang chủ - Store88",
  description: "Generated by create next app",
  icons: {
    icon: "https://res.cloudinary.com/tulam120604/image/upload/v1745568585/by1qzllthq4ypulyfrey.png", // hoặc "/icon.png"
  },
};

const poppins = Inter({
  subsets: ["vietnamese"],
  weight: ["400"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
