import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "./(Pages)/Header/page";
import Footer from "./(Pages)/Footer/page";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fruit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Header/>
        <main className="mt-[100px]">
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
